---
 - hosts: all
   gather_facts: true
   become_user: true
   connectivity: ssh
   tasks:
     - name: installing git
       apt: name='{{item}}' state=present
       with_items: 
          - git
       async: 5
       poll: 2
       delegate_to: host1

     - name: installing maven and java
       apt: name='{{item}}' state=present path=/opt
       with_items:
          - maven
          - open-jdk-8-jdk
       async: 5
       poll: 3
       delegate_to: host2

     - name: installing docker
       apt: name='{{item}}' state=present
       with_items: 
          - docker.io
       async: 5
       poll: 2
       delegate_to: host3

